x-customizable-image: &customizable_image
  # By default the image used only contains the `frappe` and `erpnext` apps.
  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
  pull_policy: ${PULL_POLICY:-always}
  restart: ${RESTART_POLICY:-unless-stopped}

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: [*depends_on_configurator, *customizable_image]
  volumes:
    - ${SITES_PATH:-/opt/frappe/sites}:/home/frappe/frappe-bench/sites

services:
  configurator:
    <<: *backend_defaults
    platform: linux/amd64
    entrypoint:
      - bash
      - -c
    # add redis_socketio for backward compatibility
    command:
      - >
        mkdir -p sites;

        [ -f sites/common_site_config.json ] || echo "{}" > sites/common_site_config.json;

        ls -1 apps > sites/apps.txt;

        bench set-config -g db_host $$DB_HOST;

        bench set-config -gp db_port $$DB_PORT;

        bench set-config -g redis_cache "redis://$$REDIS_CACHE";

        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";

        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";

        bench set-config -gp socketio_port $$SOCKETIO_PORT;

        bench set-config -g chromium_path /usr/bin/chromium-headless-shell;

    environment:
      DB_HOST: ${DB_HOST:-}
      DB_PORT: ${DB_PORT:-}
      REDIS_CACHE: ${REDIS_CACHE:-}
      REDIS_QUEUE: ${REDIS_QUEUE:-}
      SOCKETIO_PORT: 9000

    depends_on: {}

    restart: on-failure

  backend:
    <<: *backend_defaults
    platform: linux/amd64
    environment:
      GUNICORN_THREADS: ${GUNICORN_THREADS:-4}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}